id: P000288
initial_creation_type: ocr
created_at: 21/02/2020
last_modified_at: 2021-12-16 15:11:09.729084
source_metadata:
  id: bdr:W1PD137889
  title: མཉམ་མེད་ཇོ་བོ་རྗེ་དཔལ་ལྡན་ཨ་ཏི་ཤའི་རྣམ་པར་ཐར་པ་ཕྱོགས་བསྡུས་དད་པའི་འཇུག་ངོགས།
  author: ''
  volumes:
    e8153f4dc5624c4b8d3409386b0229ed:
      image_group_id: I2PD18897
      title: Volume 1 of mnyam med jo bo rje dpal ldan a ti sha'i rnam par thar pa
        phyogs bsdus dad pa'i 'jug ngogs/
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
